services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: vessel_metrics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - services-net

networks:
  services-net:
    driver: bridge
