services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: vessel_metrics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - services-net

  vessel-metrics-service:
    build: .
    image: vessel-metrics-service:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vessel_metrics
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - services-net

networks:
  services-net:
    driver: bridge
